# Generated by Django 4.0.4 on 2022-04-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_alter_book_options_alter_book_cover_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
